server:
  port: 3322

spring:
  data:
    maria:
      jdbc-url: jdbc:mariadb://wititimer.ch8cyufsil5e.ap-northeast-2.rds.amazonaws.com:3306/timer3?useUnicode=yes&characterEncoding=UTF-8
      driver-class-name: org.mariadb.jdbc.Driver
      username: admin
      password: password
  jpa:
    properties:
      hibernate:
        #show_sql: true
        format_sql: true
        temp:
          use_jdbc_metadata_defaults: false
    generate-ddl: true
